### ISSUE TITLE
seed.sql

### ISSUE THREAD

**Issue by WesleyYep** [OpenCityProject/ocp-docker#3]
Hey just wondering I remember Ben mentioning that all the .sql files get run in alphabetical order when docker-compose up is run
I've been playing around and it doesn't seem like seed.sql is being executed?
Any ideas?

**Comment by WesleyYep** [comment]
this is looking at the dbdesign branch btw

**Comment by ayroblu** [comment]
Edit docker compose to *.sql solves (though currently its just commands in order)
